apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod

on:
  workflow_dispatch: {}

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: ecr-go-repo
          artifact-id: 8ea1fc15-9886-4f84-9ac7-22d8476d29b9
          target-environment: Pre-Prod